spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop
    username: root
    password: rootroot
  jpa:
    hibernate.ddl-auto: update
    show-sql: false
